### ISSUE TITLE
Discussion: Alternative name for --stanza?

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#76]
I'm not sure if there's any benefit to use "stanza" instead of the more established "cluster" name for Postgres database collections.

I understand "server" might be misleading in cloud environments where they can be very dynamic and short-lived.

**Comment by dwsteele** [comment]
The thinking here is that stanza can refer to a number of clusters: primaries, replicas, development, reporting servers. --cluster could be confusing on the command line due to it's usage in Ubuntu for psql, etc.  The primary/replica clusters for a single db might easily have different names, and the stanza might be something else entirely.

Stanza is also used in backup software such as Bacula and Amanda.  To be honest, I don't love the term - it's just the best we could come up with.

**Comment by terrorobe** [comment]
Point taken - after playing around with wal shipping/backups from replicated clusters this is probably the least confusable option.
