### ISSUE TITLE
Move from psql exec to DBI?

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#98]
As mentioned in #94

Not sure if this gains us too much - since we need to have postgres permissions to access the data directory we can almost certainly expect that psql exists on the server and allows us to talk to the database.

If we move to DBI we need to make sure that it behaves identically to psql when it comes to defaults (socket discovery, .pgpass parsing, etc.) - not sure if all this functionality is present in libpq and wired up correctly in the DBI driver.

What I'd certainly like to see is moving away from implied defaults that only can be changed awkwardly (e.g. adding ``--port`` to psql cmdline options instead of it being a discrete setting that gets interpolated correctly by backrest)

If we had that, we could identify databases by a port instead of a db-path (and fetch the data_directory from postgres itself)

**Comment by dwsteele** [comment]
The command line stuff is a holdover from when backrest used entirely command line tools.  Seriously - go look at the File object in 0.18 (https://github.com/pgmasters/backrest/blob/9acbba173e65f40d6032ed47a1760ec48e383b91/pg_backrest_file.pm).

Ticket #20 has been around for a long time to address this issue - just hasn't been that big a deal.

But I agree with you that more discovery would be better.  I'll paste your comment into #20 and close this issue.

**Comment by dwsteele** [comment]
This was implemented in 23e6267.  DBD::Pg supports socket discovery and .pgpass.  I'll admit that I've only tested socket discovery as I don't think .pgpass makes sense in the context of backup since it must be run as the cluster owner who should have peer auth to the db.  Still, .pgpass should work fine as it is libpq feature.

As for auto-discovery of db-path: that sounds good but won't work for restores when the database is shutdown.  Instead I've opened #121 which does some cross-checking to make sure settings make sense.

I'd prefer things were setup in advance for restore (by working for backup) so there are no nasty surprises when thrust into a emergency restore scenario.

**Comment by terrorobe** [comment]
ack regarding db-path. Makes me sad but short of rewriting the configuration file on first connect I don't see any way to make this work either in situations where the database is downed.

And having backrest behave correctly only in fair weather situations beats it's purpose ;)
